// <auto-generated />
using System;
using ABBMailing.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABBMailing.Migrations
{
    [DbContext(typeof(MailingContext))]
    partial class MailingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("ABBMailing.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool?>("Subscribed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("UnsubscribeToken")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UnsubscribeToken")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ABBMailing.Models.AddressTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<int>("TopicId");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("TopicId");

                    b.ToTable("AddressTopic");
                });

            modelBuilder.Entity("ABBMailing.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("ABBMailing.Models.AddressTopic", b =>
                {
                    b.HasOne("ABBMailing.Models.Address", "Address")
                        .WithMany("AddressTopics")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ABBMailing.Models.Topic", "Topic")
                        .WithMany("AddressTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
